apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: mariadb
          volumeMounts:
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d
          volumes:
            - name: custom-init-scripts
              configMap:
                name: {{ .Release.Name }}-init-sql
